- name: Deploy on Raspberry Pi
  hosts: raspberry_pies
  become: yes
  tasks:
    - name: Stop
      shell: "killall /home/vladas/glavpetuh || true"
      args:
        executable: /bin/bash

    - name: Copy binary
      copy:
        src: ../glavpetuh/target/aarch64-unknown-linux-gnu/release/glavpetuh
        dest: /home/vladas/glavpetuh
        mode: '0755'
    
    - name: Copy .env config
      copy:
        src: ../glavpetuh/.env
        dest: /home/vladas/.env
        mode: '0644'

    - name: Run
      shell: |
        nohup /home/vladas/glavpetuh > /var/log/glavpetuh.log 2>&1 &
      args:
        executable: /bin/bash
    