- name: Install soft
  hosts: all
  become: yes
  tasks:
    - name: Install packages
      package:
        name:
          - duf
          - ncdu
          - acpi
          - brightnessctl
        state: present
        update_cache: yes
