apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-longhorn-pvc
  labels:
    app: minecraft
  namespace: minecraft
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi
  volumeName: minecraft-longhorn-pv
