apiVersion: v1
kind: Service
metadata:
  labels:
    app: minecraft
  name: minecraft
  namespace: minecraft
spec:
  ports:
    - name: server
      port: 25565
      targetPort: server
  selector:
    app: minecraft
  type: LoadBalancer
