apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-longhorn-pvc
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi
  volumeName: prometheus-longhorn-pv
