# prometheus-config.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: "pci3"
        static_configs:
          - targets: ["192.168.0.103:9100", "192.168.0.103:9256", "192.168.0.103:9900"]
              
      - job_name: "tc1"
        static_configs:
          - targets: ["192.168.0.201:9100", "192.168.0.201:9256"]

      - job_name: "tc2"
        static_configs:
          - targets: ["192.168.0.202:9100", "192.168.0.202:9256"]
