apiVersion: v1
kind: ConfigMap
metadata:
  name: palworld-cm
  namespace: palworld
data:
  PUID: "1000"
  PGID: "1000"
  PORT: "8211"  # Optional but recommended
  PLAYERS: "16"  # Optional but recommended
  SERVER_PASSWORD: "SERVER_PASSWORD"  # Optional but recommended
  MULTITHREADING: "true"
  RCON_ENABLED: "true"
  RCON_PORT: "25575"
  TZ: UTC
  COMMUNITY: "false"  # Enable this if you want your server to show up in the community servers tab, USE WITH SERVER_PASSWORD!
  SERVER_NAME: "World of Petushara"
  SERVER_DESCRIPTION: ""
  DISCORD_WEBHOOK_URL: "https://discord.com/api/webhooks/..."
  BASE_CAMP_WORKER_MAX_NUM: "50"
  BASE_CAMP_MAX_NUM_IN_GUILD: "10"
  BUILD_OBJECT_DETERIORATION_DAMAGE_RATE: "0.0"
  NIGHTTIME_SPEEDRATE: "2.0"
