apiVersion: v1
kind: Service
metadata:
  labels:
    app: palworld
  name: palworld
  namespace: palworld
spec:
  ports:
    - name: server
      port: 8211
      protocol: UDP
      targetPort: server
    - name: query
      port: 27015
      protocol: UDP
      targetPort: query
  selector:
    app: palworld
  type: LoadBalancer
