---
- name: Stop and remove Grafana
  hosts: pi
  become: true
  tasks:

    - name: Stop and disable Grafana service
      ansible.builtin.systemd:
        name: grafana-server
        enabled: false
        state: stopped

    - name: Remove Grafana APT repository
      ansible.builtin.apt_repository:
        repo: "deb https://packages.grafana.com/oss/deb stable main"
        filename: grafana
        state: absent

    - name: Remove Grafana GPG key
      ansible.builtin.apt_key:
        url: https://packages.grafana.com/gpg.key
        state: absent

    - name: Uninstall Grafana
      ansible.builtin.apt:
        name: grafana
        state: absent

    - name: Uninstall gnupg
      ansible.builtin.apt:
        name: gnupg
        state: absent

    - name: Remove leftover Grafana directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - /etc/grafana
        - /var/lib/grafana
        - /var/log/grafana
