services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    network_mode: host  # Simplest way to expose port 8096 directly
    volumes:
      - ./config:/config
      - ./cache:/cache
      - ./media:/media
      - /mnt/hdd4TB:/media/hdd4TB
    restart: unless-stopped
    environment:
      - TZ=Europe/Vilnius  # Set to your time zone

#  mkdir -p ~/jellyfin/config ~/jellyfin/cache ~/jellyfin/media
#  ln -s /mnt/hdd4TB ~/jellyfin/media/hdd4TB
# sudo usermod -aG docker dietpi
# docker compose up -d

