apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jellyfin-ingress
  namespace: default
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  tls:
    - hosts:
        - jellyfin.vladas.xyz
      secretName: vladas.xyz-tls
  rules:
    - host: jellyfin.vladas.xyz
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: jellyfin-external
                port:
                  number: 8096
---
apiVersion: v1
kind: Endpoints
metadata:
  name: jellyfin-external
  namespace: default
subsets:
  - addresses:
      - ip: 192.168.0.103
    ports:
      - port: 8096
---
apiVersion: v1
kind: Service
metadata:
  name: jellyfin-external
  namespace: default
spec:
  clusterIP: None
  ports:
    - port: 8096
      targetPort: 8096


# kubectl create secret tls vladas.xyz-tls --cert=vladas.xyz.pem --key=vladas.xyz