- name: Apply Kubernetes
  hosts: localhost
  tasks:
    - name: Create namespace
      command: >
        kubectl create namespace monitoring

    - name: Load dashboard
      command: >
        kubectl create configmap grafana-dashboard-json \
        --from-file=my-dashboard.json={{ playbook_dir }}/dashboard.yml \
        -n monitoring

    - name: Assign grafana role
      command: >
        kubectl label node mb12 role=grafana

    - name: Apply Kubernetes
      command: >
        kubectl apply --recursive --filename={{ playbook_dir }}/../kubernetes
      register: kubectl_output

    - name: Show kubectl output
      debug:
        msg: "{{ kubectl_output.stdout_lines }}"
