apiVersion: v1
kind: Namespace
metadata:
  name: misc
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: registry-longhorn-pv
  namespace: misc
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  csi:
    driver: driver.longhorn.io
    volumeHandle: registry  # <-- This must match the name of the volume in Longhorn exactly
  storageClassName: longhorn
  persistentVolumeReclaimPolicy: Retain
