apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registry-longhorn-pvc
  labels:
    app: registry
  namespace: misc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi
  volumeName: registry-longhorn-pv
