apiVersion: v1
kind: PersistentVolume
metadata:
  name: palworld-longhorn-pv
  namespace: palworld
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  csi:
    driver: driver.longhorn.io
    volumeHandle: palworld  # <-- This must match the name of the volume in Longhorn exactly
  storageClassName: longhorn
  persistentVolumeReclaimPolicy: Retain
