- name: Install and start Grafana
  hosts: cp
  become: true
  tasks:
    - name: Install gnupg (required for apt_key)
      apt:
        name: gnupg
        state: present

    - name: Add Grafana GPG key
      apt_key:
        url: https://packages.grafana.com/gpg.key
        state: present

    - name: Add Grafana APT repository
      apt_repository:
        repo: "deb https://packages.grafana.com/oss/deb stable main"
        filename: grafana
        state: present

    - name: Install Grafana
      apt:
        name: grafana
        state: present

    # ansible-galaxy collection install community.grafana

    - name: Ensure Grafana is running
      systemd:
        name: grafana-server
        enabled: true
        state: started

    - name: Wait for Grafana
      wait_for:
        timeout: 5

    - name: Create prometheus datasource
      community.grafana.grafana_datasource:
        name: prometheus
        grafana_url: http://localhost:3000
        ds_type: prometheus
        ds_url: http://localhost:9090
        is_default: true

    # - name: Import Grafana dashboard
    #   community.grafana.grafana_dashboard:
    #     grafana_url: http://localhost:3000
    #     grafana_user: admin
    #     grafana_password: admin
    #     state: present
    #     commit_message: Updated by ansible
    #     overwrite: true
    #     path: "dashboard.json"

    # - name: Create or update a Grafana user
    #   community.grafana.grafana_user:
    #     url: http://localhost:3000
    #     url_username: admin
    #     url_password: admin
    #     name: "Admin"
    #     email: batman@gotham.city
    #     login: vladas
    #     password: admin
    #     is_admin: true
    #     state: present
