apiVersion: v1
kind: Namespace
metadata:
  name: lanraragi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: lanraragi-longhorn-pv
  namespace: lanraragi
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  csi:
    driver: driver.longhorn.io
    volumeHandle: lanraragi  # <-- This must match the name of the volume in Longhorn exactly
  storageClassName: longhorn
  persistentVolumeReclaimPolicy: Retain
