apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lanraragi-longhorn-pvc
  labels:
    app: lanraragi
  namespace: lanraragi
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi
  volumeName: lanraragi-longhorn-pv
