apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-longhorn-pv
  namespace: monitoring
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  csi:
    driver: driver.longhorn.io
    volumeHandle: grafana  # <-- This must match the name of the volume in Longhorn exactly
  storageClassName: longhorn
  persistentVolumeReclaimPolicy: Retain
