apiVersion: v1
kind: Namespace
metadata:
  name: komga
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: komga-longhorn-pv
  namespace: komga
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  csi:
    driver: driver.longhorn.io
    volumeHandle: komga  # <-- This must match the name of the volume in Longhorn exactly
  storageClassName: longhorn
  persistentVolumeReclaimPolicy: Retain
