apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: komga-longhorn-pvc
  labels:
    app: komga
  namespace: komga
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi
  volumeName: komga-longhorn-pv
