- name: Upgrade
  hosts: linux
  become: true
  tasks:
    - name: Upgrade
      apt:
        clean: true
        autoclean: true
        autoremove: true
        update_cache: true
        upgrade: true
