- name: Run CPU and memory benchmarks using sysbench
  hosts: all
  become: true
  vars:
    separator: "----------------------------------------"

  tasks:
    - name: Ensure sysbench is installed
      apt:
        name: sysbench
        state: present

    - name: Get number of CPU cores
      shell: nproc
      register: cpu_cores

    - name: Run CPU benchmark (1 thread)
      command: sysbench cpu --threads=1 run
      register: cpu_1t

    - name: Run CPU benchmark (4 threads)
      command: sysbench cpu --threads=4 run
      register: cpu_4t

    - name: Run CPU benchmark (all cores)
      command: sysbench cpu --threads={{ cpu_cores.stdout }} run
      register: cpu_all

    - name: Run memory benchmark
      command: sysbench memory run
      register: mem_test

    - name: Print benchmark results
      debug:
        msg: |
          1:  {{ cpu_1t.stdout_lines | select('search', 'events per second') | list }}
          4: {{ cpu_4t.stdout_lines | select('search', 'events per second') | list }}
          {{ cpu_cores.stdout }}: {{ cpu_all.stdout_lines | select('search', 'events per second') | list }}
          memory: {{ cpu_all.stdout_lines | select('search', 'number of events') | list }}

    - name: Run internet benchmark
      command: speedtest-cli --simple
      register: internet_test

    - name: Print internet benchmark results
      debug:
        msg: |
          {{ internet_test.stdout }}
