- name: Install and start Grafana
  hosts: cp
  become: true
  tasks:
    - name: Install gnupg (required for apt_key)
      apt:
        name: gnupg
        state: present

    - name: Add Grafana GPG key
      apt_key:
        url: https://packages.grafana.com/gpg.key
        state: present

    - name: Add Grafana APT repository
      apt_repository:
        repo: "deb https://packages.grafana.com/oss/deb stable main"
        filename: grafana
        state: present

    - name: Install Grafana
      apt:
        name: grafana
        state: present

    - name: Ensure Grafana is running
      systemd:
        name: grafana-server
        enabled: true
        state: started
