- name: Install soft
  hosts: all
  become: true
  tasks:
    - name: Install soft
      package:
        name:
          - duf
          - ncdu
          - htop
          - acpi
          - brightnessctl
        state: present
        update_cache: true
