- name: Run IOPS benchmark using fio
  hosts: all
  vars:
    fio_runtime: 30
    fio_numjobs: 4
    fio_iodepth: 64
    fio_bs: 4k
    fio_rw: randread
    fio_size: 1G
    fio_output_file: "{{ ansible_env.HOME }}/fio_output.txt"

  tasks:
    - name: Install fio
      become: "{{ ansible_os_family != 'Darwin' }}"
      ansible.builtin.package:
        name: fio
        state: present

    - name: Create fio job file from template
      ansible.builtin.template:
        src: fio-job.fio.j2
        dest: "{{ ansible_env.HOME }}/fio-job.fio"

    - name: Run fio benchmark
      ansible.builtin.shell: |
        fio {{ ansible_env.HOME }}/fio-job.fio > {{ fio_output_file }}
      args:
        executable: /bin/bash

    - name: Read fio output content
      ansible.builtin.slurp:
        src: "{{ fio_output_file }}"
      register: fio_output_raw

    - name: Print fio result
      ansible.builtin.debug:
        msg: "{{ fio_output_raw['content'] | b64decode }}"

    - name: Display IOPS results only
      ansible.builtin.debug:
        msg: >-
          {{
            (fio_output_raw['content'] | b64decode)
            | regex_search('IOPS=([0-9.]+[kM]?)', '\\1')
          }}
