---
- name: Stop and uninstall Nginx
  hosts: all
  become: true
  tasks:

    - name: Check if Nginx is installed
      ansible.builtin.command: which nginx
      register: nginx_check
      changed_when: false
      failed_when: false

    - name: Stop Nginx service if installed
      ansible.builtin.service:
        name: nginx
        state: stopped
        enabled: false
      when: nginx_check.rc == 0

    - name: Uninstall Nginx package
      ansible.builtin.package:
        name: nginx
        state: absent
