- import_playbook: apt_upgrade.yml
# - import_playbook: install_soft.yml
# - import_playbook: prometheus/node_exporter.yml
# - import_playbook: prometheus/process_exporter.yml
# - import_playbook: prometheus/laptop_exporter.yml
# - import_playbook: prometheus/install_prometheus.yml
# - import_playbook: grafana/grafana.yml
# - import_playbook: nginx.yml
