- name: Setup Dedicated Valheim Server Script
  hosts: valheim

  tasks:
    - name: Update apt cache and install Git and net-tools
      become: true
      apt:
        name:
          - git
          - net-tools
        state: present
        update_cache: true

    - name: Clone Dedicated Valheim Server Script repository
      git:
        repo: https://github.com/Nimdy/Dedicated_Valheim_Server_Script.git
        version: 1353ec50e719c81eb2de359023de619dddda614a
        dest: ~/valheim

    - name: Set execute permissions for njordmenu.sh
      file:
        path: ~/valheim/njordmenu.sh
        mode: '0755'
        state: file
